'use client'
import { ThemeProvider } from 'next-themes'
import './globals.css'
import type { Metadata } from 'next'
import Loading from './loading'
import SupabaseProvider from './_providers/SupabaseProvider'
import UserProvider from './_providers/UserProvider'
import ModalProvider from './_providers/ModelProvider'
import NavigationBar from './_components/NavigationBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SupabaseProvider>
          <UserProvider>
            <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
              <div className='mx-auto max-w-7xl h-screen bg-background'>
                <ModalProvider />
                <NavigationBar />
                {children}
              </div>
            </ThemeProvider>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
