import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function Home({ children }: { children: React.ReactNode }) {
    return (
        <div>test222
            <div>{children}</div>
        </div>
    )
}
